[project]
name = "EvacuationPy"
version = "0.0.1"
description = "Evacuation modeling"
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
	'scipy == 1.10',
	'matplotlib == 3.7',
	'ruff == 0.0.272',
	'pytest == 7.3.2',
	'autopep8 == 2.0.2'
]

[tool.ruff]
target-version = "py311"
line-length = 120

[tool.autopep8]
max_line_length = 120
aggressive = 3
recursive = true