name: Run tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.8", "3.11"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[all]
      - uses: chartboost/ruff-action@v1
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "."
      - uses: jakebailey/pyright-action@v1
      - name: Test with pytest
        run: pytest -n logical
